name: Build CI
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  PROGRAM_NAME: GARbro

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Add MSbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build the solution
        run: msbuild ${{ env.PROGRAM_NAME }}.sln /t:restore,build /p:Configuration=Release /p:Platform="Any CPU"

      - name: Set short SHA
        id: vars
        shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROGRAM_NAME }}-beta-${{ steps.vars.outputs.sha_short }}
          path: bin/Release/net48